### ISSUE TITLE
Projektseite FH

### ISSUE THREAD

**Issue by SimoKutlin** [loggrio/loggr.io#136]

**Comment by Iniesta8** [comment]
Was ist damit gemeint?

**Comment by SimoKutlin** [comment]
Auf der Homepage der FH kann man sich Projekte ansehen die verwirklicht wurden und dass da zusätzlich zum Artikel für den Jahresbericht (apropos, hast du da nicht mal was geschrieben gehabt?) noch so eine Seite erstellt wird.
